add_missing_ingredients:
  name: Fehlende Zutaten zu Bring hinzufügen
  description: Packt die fehlenden Zutaten eines spezifischen Rezepts auf die Bring-Liste.
  fields:
    ingredients:
      name: Zutaten
      description: Die Liste der fehlenden Zutaten als Text oder Array.
      required: true
      selector:
        object: {}
